# Generated by Django 5.0.2 on 2024-03-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_exam_options_exam_created_exam_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='stege',
            new_name='stage',
        ),
    ]
